backend:
  name: github
  repo: arthurdasler/portfolio
  branch: main

media_folder: "IMG/" # где Netlify CMS будет хранить картинки
public_folder: "/IMG/"

collections:
  - name: "projects"
    label: "Проекты"
    label_singular: "Проект"
    folder: "data" # где будут храниться json-файлы (можешь изменить путь)
    extension: "json"
    format: "json"
    create: true
    slug: "{{id}}"
    fields:
      - { label: "ID", name: "id", widget: "string" }
      - { label: "Название проекта", name: "title", widget: "string" }
      - { label: "Описание", name: "description", widget: "text" }
      - { label: "Период", name: "period", widget: "string" }
      - { label: "Позиция", name: "position", widget: "string" }
      - { label: "Логотип", name: "logo", widget: "image" }
      - label: "Изображения"
        name: "images"
        widget: "list"
        field: { label: "Изображение", name: "image", widget: "image" }
      - { label: "Markdown файл", name: "markdown", widget: "string" }
